// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhKsHuC7Ld_RX2Tsl4kbcUeSB4Icdy_PI',
    appId: '1:538000452693:web:fa7aa6878d5891eba738dc',
    messagingSenderId: '538000452693',
    projectId: 'ecocarga-drive',
    authDomain: 'ecocarga-drive.firebaseapp.com',
    storageBucket: 'ecocarga-drive.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqc01CoFjx03-U1s-cC78JHzzOH5DAY40',
    appId: '1:538000452693:android:f0634f8c38ef09fda738dc',
    messagingSenderId: '538000452693',
    projectId: 'ecocarga-drive',
    storageBucket: 'ecocarga-drive.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9b22Q5Uu8ha6L3a-FFYke8nDjOseEJn8',
    appId: '1:538000452693:ios:8c639e7696a7cda8a738dc',
    messagingSenderId: '538000452693',
    projectId: 'ecocarga-drive',
    storageBucket: 'ecocarga-drive.firebasestorage.app',
    androidClientId: '538000452693-cnlpcv3m0ojg0qsfb89ncl1j60b1ndrr.apps.googleusercontent.com',
    iosClientId: '538000452693-1mnkpjekh32h1a1gsg54hp479khfee78.apps.googleusercontent.com',
    iosBundleId: 'com.echnelapp.localdriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9b22Q5Uu8ha6L3a-FFYke8nDjOseEJn8',
    appId: '1:538000452693:ios:8c639e7696a7cda8a738dc',
    messagingSenderId: '538000452693',
    projectId: 'ecocarga-drive',
    storageBucket: 'ecocarga-drive.firebasestorage.app',
    androidClientId: '538000452693-cnlpcv3m0ojg0qsfb89ncl1j60b1ndrr.apps.googleusercontent.com',
    iosClientId: '538000452693-1mnkpjekh32h1a1gsg54hp479khfee78.apps.googleusercontent.com',
    iosBundleId: 'com.echnelapp.localdriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhKsHuC7Ld_RX2Tsl4kbcUeSB4Icdy_PI',
    appId: '1:538000452693:web:b7fbd886717a94aaa738dc',
    messagingSenderId: '538000452693',
    projectId: 'ecocarga-drive',
    authDomain: 'ecocarga-drive.firebaseapp.com',
    storageBucket: 'ecocarga-drive.firebasestorage.app',
  );

}